# Generated by Django 4.2.30 on 2026-05-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='Пользователь ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('user_message', models.TextField(verbose_name='Сообщение пользователя')),
                ('bot_answer', models.TextField(verbose_name='Ответ бота')),
                ('language', models.CharField(default='ru', max_length=5, verbose_name='Язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'История чата',
                'verbose_name_plural': 'История чата',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ сұрақтары'},
        ),
    ]
