# Generated by Django 4.2.30 on 2026-05-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_chathistory_alter_faq_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
